---
--- Generated by Luanalysis
--- Created by Administrator.
--- DateTime: 2021/7/15 8:42
---
conf_arr={}

--设置redis ip
conf_arr.resty_redis = {hostname="127.0.0.1",port=6379}
--站点key
conf_arr.site_data_key="site::data::key"